title: Khoa's Blog
description: My Personal Stack Problems
author: Khoa Nguyen
github: https://github.com/congkhoa
about: I am Python developer, System Admin.
disqus_shortname: khoablog
google_analytics: UA-81941010-1

enableTags: true
tagarray: [python, mariadb, golang]

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: khoanc
  fb_appid: 161872040887306

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/congkhoa
    - text: XML Feed
      url: /feed.xml

url: "http://congkhoa.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist